### ISSUE TITLE
SilverStripe 4 Support

### ISSUE THREAD

**Issue by wilr** [robingram/silverstripe-unused-file-report#5]
Hey @robingram, thanks for writing this awesome module. I'm looking at using this as part of a 4.0 upgrade and audit to see what's used - I'm happy to upgrade it but just checking you haven't started on the update of this module yet? Otherwise I'll start a PR.

**Comment by robingram** [comment]
Thanks @wilr! No I haven't started looking at this yet. If you'd like to take a look that would be awesome but be aware that it could be a fairly large job given that the Asset system has changed quite a lot.

I also noticed that there is File and Link tracking functionality in 4.2+ (I think) but that is more for broken links than unused files as far as I know.

**Comment by robingram** [comment]
@wilr Thanks for all your work on this.
